language: elixir
elixir:
  - 1.7
otp_release:
  - 20.1
sudo: false
services:
  - postgresql
notifications:
  recipients:
    - bruce.williams@cargosense.com
env:
  - MIX_ENV=test
before_script:
  - mix ecto.setup
